# Generated by Django 4.1.7 on 2023-06-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=25)),
                ('mail_contacto', models.EmailField(max_length=254)),
                ('asunto_contacto', models.CharField(max_length=30)),
                ('texto_contacto', models.CharField(max_length=700)),
            ],
            options={
                'verbose_name_plural': 'Contacto',
            },
        ),
        migrations.CreateModel(
            name='Playas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_playa', models.CharField(max_length=30)),
                ('descripcion_playa', models.CharField(max_length=600)),
                ('transporte_publico', models.CharField(max_length=15)),
                ('servicios_playa', models.CharField(max_length=15)),
                ('terreno', models.CharField(max_length=10)),
                ('distancia_ciudad', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Playas',
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('texto', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='Pueblos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pueblo', models.CharField(max_length=30)),
                ('descripcion_pueblo', models.CharField(max_length=600)),
                ('transporte_publico', models.CharField(max_length=15)),
                ('distancia_ciudad_pueblo', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Pueblos',
            },
        ),
        migrations.CreateModel(
            name='Senderismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ruta', models.CharField(max_length=20)),
                ('dificultad', models.CharField(max_length=10)),
                ('recorrido', models.CharField(max_length=15)),
                ('altitud_max', models.CharField(max_length=15)),
                ('localidad_origen', models.CharField(max_length=20)),
                ('descripcion_ruta', models.CharField(max_length=700)),
            ],
            options={
                'verbose_name_plural': 'Senderismo',
            },
        ),
        migrations.CreateModel(
            name='SobreNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_sobre_nosotros', models.CharField(max_length=40)),
                ('texto_sobre_nosotros', models.CharField(max_length=700)),
            ],
            options={
                'verbose_name_plural': 'Sobre Nosotros',
            },
        ),
    ]
