# Generated by Django 4.1.7 on 2023-06-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preentrega3App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorías',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoría', models.CharField(max_length=30)),
                ('descripción_categoría', models.CharField(max_length=150)),
            ],
        ),
    ]
