# Generated by Django 4.1.7 on 2023-06-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preentrega3App', '0003_pueblos_fecha_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pueblos',
            name='usuario_creacion',
            field=models.CharField(default='', max_length=20),
        ),
    ]
