# Generated by Django 4.1.7 on 2023-06-27 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Preentrega3App', '0004_pueblos_usuario_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='playas',
            name='fecha_creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='playas',
            name='usuario_creacion',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='senderismo',
            name='fecha_creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='senderismo',
            name='usuario_creacion',
            field=models.CharField(default='', max_length=20),
        ),
    ]
