# Generated by Django 4.1.7 on 2023-06-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preentrega3App', '0011_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, default='avatares/avatar_pred.png', null=True, upload_to='avatares'),
        ),
    ]
