# Generated by Django 4.1.7 on 2023-06-28 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preentrega3App', '0013_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='link_web',
        ),
    ]
