# Generated by Django 4.1.7 on 2023-06-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preentrega3App', '0015_sobrenosotros_fecha_creado_userprofile_link_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senderismo',
            name='usuario_creacion',
            field=models.CharField(default='', max_length=20),
        ),
    ]
