# Generated by Django 4.1.7 on 2023-06-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preentrega3App', '0016_alter_senderismo_usuario_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
