# Generated by Django 4.1.7 on 2023-06-29 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Preentrega3App', '0017_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preentrega3App.userprofile'),
        ),
    ]
