# Generated by Django 4.1.7 on 2023-06-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preentrega3App', '0020_rename_presentacion_cabecera_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cabecera',
        ),
        migrations.RenameField(
            model_name='playas',
            old_name='servicios_playa',
            new_name='desc_abreviada',
        ),
        migrations.RemoveField(
            model_name='playas',
            name='distancia_ciudad',
        ),
        migrations.RemoveField(
            model_name='playas',
            name='terreno',
        ),
    ]
