# Generated by Django 4.1.7 on 2023-06-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preentrega3App', '0021_delete_cabecera_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playas',
            old_name='desc_abreviada',
            new_name='desc_abreviada_playa',
        ),
        migrations.RemoveField(
            model_name='playas',
            name='transporte_publico',
        ),
    ]
