# Generated by Django 4.1.7 on 2023-06-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preentrega3App', '0023_alter_playas_desc_abreviada_playa_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorías',
        ),
        migrations.RemoveField(
            model_name='pueblos',
            name='distancia_ciudad_pueblo',
        ),
        migrations.RemoveField(
            model_name='pueblos',
            name='transporte_publico',
        ),
        migrations.RemoveField(
            model_name='senderismo',
            name='recorrido',
        ),
        migrations.AddField(
            model_name='pueblos',
            name='desc_abreviada_pueblo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='senderismo',
            name='desc_abreviada_ruta',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pueblos',
            name='descripcion_pueblo',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='senderismo',
            name='descripcion_ruta',
            field=models.CharField(max_length=1200),
        ),
    ]
