# Generated by Django 4.1.7 on 2023-06-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preentrega3App', '0024_delete_categorías_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pueblos',
            name='img_pueblo',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='senderismo',
            name='img_senderismo',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
